package com.redhat.gpe.refarch.bpm_rulesMgmt.processTier;

import com.redhat.gpe.refarch.bpm_rulesMgmt.domain.Policy;
import com.redhat.gpe.refarch.bpm_rulesMgmt.domain.PolicyTracker;

global PolicyTracker pTracker;

rule "testRule"
  when
      $policy : Policy()
  then
     int count = pTracker.getProcessedCount();
     count++;
     pTracker.setProcessedCount(count);
     String statement = "testRule() ... just executed: count = "+count);
     System.out.println(statement);
end  

