package com.redhat.gpe.refarch.bpm_rulesMgmt.processTier;

import com.redhat.gpe.refarch.bpm_rulesMgmt.domain.Policy;
import com.redhat.gpe.refarch.bpm_rulesMgmt.domain.PolicyGlobal;

global PolicyGlobal pGlobal;

rule "testRule"
  when
      $policy : Policy()
  then
    int sleepTime = 1000;
     if(pGlobal != null) {
         sleepTime = pGlobal.getSleepTime();
    }
    System.out.println("testRule() sleepTime = "+sleepTime);
    Thread.sleep(sleepTime);
    System.out.println("testRule() done sleeping. kieSessionId = "+drools.getWorkingMemory().getId());
    
end  

