package com.redhat.gpe.refarch.bpm_rulesMgmt.processTier;

import com.redhat.gpe.refarch.bpm_rulesMgmt.domain.Policy;
import com.redhat.gpe.refarch.bpm_rulesMgmt.domain.PolicyTracker;

global PolicyTracker pTracker;

rule "testRule"
  when
      $policy : Policy()
  then
     if(pTracker != null) {
         int count = pTracker.getProcessedCount();
         pTracker.setProcessedCount(count++);
         System.out.println("testRule() processedCount = "+pTracker.getProcessedCount());
    } else {
        System.out.println("testRule() pTracker global is null");
    }
    Thread.sleep(5000);
    System.out.println("testRule() done sleeping");
    
end  

